task_instructions:
- ""
multi_choice_example_format:
- "{}\n{}\nAnswer with the option's letter from the given choices directly."

short_ans_example_format:
- "{}\nAnswer the question using a single word or phrase."
temperature:
- 0